- hosts: db_servers
  become: true
  collections:

    - ansible.builtin
  
  tasks:

  - name: Start MariaDB service

    systemd:

      name: started

      state: started

      enabled: true
    
    when: ansible_distribution == "Fedora"

  - name: Start MariaDB service

    service:

      name: mariadb

      state: started

      enabled: true
    
    when: ansible_distribution == "Linux Mint"

  
  - name: Check the status of the MariaDB service

    service_facts:

    register: service_state
  
  - debug:

      var: service_state.ansible_facts.services["mariadb.service"].state