---
- name: Create a directory and a file
  hosts: all
  become: true
  tasks:
  - name: Create a directory 
    ansible.builtin.file:
      path: /home/Zachary/new_dir
      state: directory 
    
  - name: Create a file
    ansible.builtin.copy:
      content: "This is Ansible file creation test only!\n"
      dest: /home/Zachary/new_dir/test_file01.txt
      mode: '0664'