- name: Install and enable samba on Linux Mint and create a Samba user account
  hosts: db_servers
  become: true
  collections:
    - community.general
  tasks:
  - name: Install Samba packages
    apt:
      name: [samba, samba-client]
      state: present
    
  - name: Enable Samba service
    ansible.builtin.service:
      name: smbd
      state: started
      enabled: true
    
  - name: Ensure sambashare group exists
    ansible.builtin.group:
      name: sambashare
      state: present

  - name: Create Samba user account
    ansible.builtin.user:
      name: sambajdoe
      password: "{{ 'Super5cretPassw0rd' | password_hash('sha512_crypt', 'SaltyFish')}}"
      shell: /sbin/nologin
      groups: sambashare
      append: yes
        
  - name: Add sambajdoe to smbpasswd file
    ansible.builtin.command: echo -ne "Super5cretPassw0rd\nSuper5cretPassw0rd\n" | smbpasswd -a -s sambajdoe