- hosts: all
  become: true
  collections:
    - ansible.builtin
  tasks:
    - name: Update package cache on Linux Minut
      apt:
        update_cache: yes
      when: ansible_distribu1tion=='Linux Mint'
    
    - name: Install apache2 package on Linux Mint
      apt:
        name: apache2
      when: ansible_distribution=='Linux Mint'
    
    - name: Update pacakge cache on Fedora
      dnf:
        update_cache: yes 
      when: ansible_distribution=='Fedora'
    
    - name: Install httpd package on Fedora
      dnf:
        name: httpd
      when: ansible_distribution == 'Fedora'

      