- hosts: all
  become: true
  collections:
    - ansible.builtin
  tasks:
  - name: Update package cache on Linux devices
    package:
      name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
      - "{{ tmux_package }}"
      - "{{ tree_package }}"
      - "{{ tree_package }}"
      state: latest
      update_cache: yes