- hosts: all
  become: true
  collections:
    - ansible.builtin
  tasks:
    - name: Update package cache on Linux Minut
      apt:
        update_cache: yes
      when: ansible_distribution=='Linux Mint'
    
    - name: Install packages on Linux Mint
      apt:
        name: 
        - apache2
        - libapache2-mod-php
        - tmux
        - tree
        state: latest
      when: ansible_distribution=='Linux Mint'
    
    - name: Update pacakge cache on Fedora
      dnf:
        update_cache: yes 
      when: ansible_distribution=='Fedora'
    
    - name: Install packages on Fedora
      dnf:
        name:
        - httpd
        - php
        - tmux
        - tree
        state: latest
      when: ansible_distribution == 'Fedora'

      
