- name: Restart ens4 interface on web1 (192.168.255.4)
  hosts: web1
  become: true
  tasks:
  - name: Restart ens4 interface
    ansible.builtin.service:
      name: NetworkManager
      state: restarted
  vars: 
    iface_name: ens4
    shell: ifdown {{ if_name }} && ifup {{ if_name }}