- name: Cisco show clock example
  hosts: r1,switches_type1
  gather_facts: false

  vars_files:
  - vars.yml
  
  tasks:
  - name: run show clock on the routers
    cisco.ios.ios_command:
      commands: show clock
    register: output
  
  - name: print output 
    ansible.builtin.debug:
      var: output.stdout_lines