- name: Retrieve the running configuration version on all routers
  hosts: routers
  gather_facts: no
  become: true
  become_method: enable
  tasks:
    - name: Run show run command on each router and save to file
      ios_command:
        commands: 
          - show running-config
      register: show_version_output
    
    - name: Save show run output to a file
      ansible.builtin.copy:
        content: "{{ show_version_output.stdout[0] }}"
        dest: "/home/user/{{ inventory_hostname }}.txt"
      
      
