---
- name: Start Apache Web Server
  hosts: web1
  become: true
  tasks:
  - name: Start Apache web server 
    ansible.builtin.service:
      name: apache2
      state: started 

  - name: Check Apache web server status
    ansible.legacy.systemd:
      name: apache2
      state: started
      enabled: yes
    register: apache_status

  - name: Print Apache web server status
    ansible.builtin.debug:
      msg: "apache2 service is {{apache_status.state}}"