---
- name: Stop Apache web server
  hosts: web1
  become: true
  tasks:
  - name: Stop Apache web sever
    ansible.builtin.service:
      name: apache2
      state: stopped
  - name: Check Apache web server    
    ansible.legacy.systemd: 
      name: apache2
      state: stopped 
    register: apache2_status
  - name: print Apache web server status  
    ansible.builtin.debug:
      msg: "apache2 service has now {{apache2_status.state}} "
