- name: Uninstall Apache web server
  hosts: web1
  become: true
  tasks:
  - name: Uninstall Apache web server
    ansible.builtin.apt:
      name: apache2
      state: absent
  - name: Print the Apache web server has successfully been installted
    ansible.builtin.debug:
      msg: "apache2 service has been successfully uninstalled"
  - name: Remove unnecessary dependencies
    ansible.builtin.apt:
      autoremove: yes
      autoclean: yes 
  - name: Ensure Apache service is stopped
    ansible.legacy.systemd:
      name: apache2
      state: stopped
    ignore_errors: yes   
    