- hosts: web_servers, db_servers
  become: true
  gather_facts: false
  tasks:
  - name: update  repository index
    ansible.builtin.apt:
      update_cache: yes
  - name: install apache2 package 
    ansible.builtin.apt:
      name: apache2
      state: absent
  - name: add php support for apache2
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
