- name: Configure Cisco IOS-XE routers' interfaces
  hosts: router_type1
  gather_facts: false

  tasks:
    - name: Load config files
      include_vars:
        ansible.builtin.file: "{{ inventory_hostname }}.yml" 
        name: r_config

    - name: Configure interfaces
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet 0/1"
          - "description {{ r_config.interface1.description }}"
          - "ip address {{ r_config.interface1.ip_address }} {{ r_config.interface1.subnet_mask }}"
          - "no shutdown"
          - "interface GigabitEthernet 0/2"
          - "description {{ r_config.interface2.description }}"
          - "ip address {{ r_config.interface2.ip_address }} {{ r_config.interface2.subnet_mask }}"
          - "no shutdown"
          - "interface GigabitEthernet 0/3"
          - "description {{ r_config.interface3.description }}"
          - "ip address {{ r_config.interface3.ip_address }} {{ r_config.interface3.subnet_mask }}"
          - "no shutdown"
