- name: Copy running-config to startup-config
  hosts: router_type1
  gather_facts: false
  tasks:
    - name: Copy running-config to startup-config
      cisco.ios.ios_command:
        commands:
          - "write memory"
