- name: Run show ip route
  hosts: router_type1
  gather_facts: false

  tasks:
    - name: Execute show ip route
      cisco.ios.ios_command:
        commands:
          - show ip route
      register: show_output

    - name: Print show ip route output
      ansible.builtin.debug:
        var: show_output.stdout_lines
