- name: Configure Cisco IOS-XE routers in group router_type1
  hosts: router_type1
  gather_facts: false

  tasks:
    - name: Configure r1, r2, and r3’s Gi0/1 interfaces on 1.1.123.0/24 subnet
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet0/1"
          - "ip address 1.1.123.{{ inventory_hostname[-1] }} 255.255.255.0"
          - "no shutdown"
          - "end"
      when: inventory_hostname in ['r1', 'r2', 'r3']

    - name: Configure r2’s Gi0/2 interface on 1.1.24.0/24 subnet
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet0/2"
          - "ip address 1.1.24.{{ inventory_hostname[-1] }} 255.255.255.0"
          - "no shutdown"
          - "end"
      when: inventory_hostname == 'r2'

    - name: Configure r4’s Gi0/1 interface on 1.1.24.0/24 subnet
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet0/1"
          - "ip address 1.1.24.{{ inventory_hostname[-1] }} 255.255.255.0"
          - "no shutdown"
          - "end"
      when: inventory_hostname == 'r4'

    - name: Configure r3 and r4’s Gi0/2 interfaces on 1.1.34.0/24 subnet
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet0/2"
          - "ip address 1.1.34.{{ inventory_hostname[-1] }} 255.255.255.0"
          - "no shutdown"
          - "end"
      when: inventory_hostname in ['r3', 'r4']

    - name: Configure r1’s G0/3 on 1.1.10.0/24 subnet and r4’s G0/3 interfaces on 1.1.40.0/24 subnet
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "interface GigabitEthernet0/3"
          - "ip address 1.1.{{ inventory_hostname[-1] }}0.{{ inventory_hostname[-1] }} 255.255.255.0"
          - "no shutdown"
          - "end"
      when: inventory_hostname in ['r1', 'r4']
