- name: Run show ip interface brief
  hosts: router_type1
  gather_facts: false

  tasks:
    - name: Execute show ip interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: show_output

    - name: Print show ip interface brief output
      ansible.builtin.debug:
        var: show_output.stdout_lines
