---
- name: Copy running-config to FTP server
  hosts: r1
  gather_facts: no
  tasks:
    - name: Run copy running-config ftp command
      cisco.ios.ios_command:
        commands:
          - copy running-config ftp:
              server: 192.168.127.151
              filename: running-config.txt
