---
- name: Ping hosts and display output
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.shell: ping -c 3 -i 0.3 -W 1 {{ item }}
      register: ping_output
      loop:
        - 192.168.127.150
        - 192.168.127.11
        - 192.168.127.12
        - 192.168.127.113
        - 192.168.127.21
        - 192.168.127.22
        - 192.168.127.123
      changed_when: false

    - name: Display output
      ansible.builtin.debug:
        var: ping_output.results | map(attribute='stdout_lines') | list
