---
- name: Run SCP command with automated passphrase
  hosts: localhost
  gather_facts: false

  vars_files:
  - vars.yml

  tasks:
    - name: Run SCP command
      ansible.builtin.expect:
        command: scp -r ./backup jdoe@192.168.127.151:/home/jdoe/.
#        command: scp -r ./backup jdoe@192.168.127.151:/.
        responses:
          "Enter passphrase for key '/home/jdoe/.ssh/id_ed25519':": "{{ passphrase_response }}"
      register: scp_output

    - name: Display SCP command output
      ansible.builtin.debug:
        var: scp_output.stdout_lines
