---
- name: Run SCP command with automated passphrase
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  vars:
    scp_servers:
      - ip: "192.168.127.151"
        path: "/home/jdoe/"
      - ip: "192.168.127.161"
        path: "/home/jdoe/"
      - ip: "192.168.127.162"
        path: "/home/jdoe/"

  tasks:
    - name: Run SCP command
      ansible.builtin.expect:
        command: "scp -r ./backup jdoe@{{ item.ip }}:{{ item.path }}"
        responses:
          "Enter passphrase for key '/home/jdoe/.ssh/id_ed25519':": "{{ passphrase_response }}"
      register: scp_output
      loop: "{{ scp_servers }}"

    - name: Display SCP command output
      ansible.builtin.debug:
        var: scp_output.stdout_lines
