---
- name: Check and create backup directory on Ansible Control machine
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check if backup directory exists
      ansible.builtin.stat:
        path: ./backup
      register: backup_dir

    - name: Create backup directory
      ansible.builtin.file:
        path: ./backup
        state: directory
      when: not backup_dir.stat.exists

- name: Backup Cisco IOS-XE Router and Switch configurations
  hosts: ios_xe_devices
#  hosts: r1
  gather_facts: false

  vars_files:
    - vars.yml

  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  tasks:
    - name: Run show run and save to a file
      cisco.ios.ios_config:
       backup: yes
       backup_options:
         filename: "{{ inventory_hostname }}_running-config.cfg"
         dir_path: ./backup/{{ timestamp }}_backup

    - name: Print message when completed
      debug: msg="Backup to local storage completed"

#- name: Run SCP command with automated passphrase
#  hosts: localhost
#  gather_facts: false

#  vars_files:
#  - vars.yml

#  tasks:
    - name: Run SCP command
      ansible.builtin.expect:
        command: scp -r ./backup jdoe@192.168.127.151:/home/jdoe/.
        responses:
          "Enter passphrase for key '/home/jdoe/.ssh/id_ed25519':": "{{ passphrase_response }}"
      register: scp_output

    - name: Display SCP command output
      ansible.builtin.debug:
        var: scp_output.stdout_lines
