---
- name: Check and create backup directory on Ansible Control machine
  hosts: localhost # Run on Ansible Control Machine, f38s1
  gather_facts: false

  tasks:
    - name: Check if backup directory exists
      stat:
        path: ./backup
      register: backup_dir

    - name: Create backup directory
      file:
        path: ./backup
        state: directory
      when: not backup_dir.stat.exists

- name: Backup Cisco IOS-XE Router and Switch configurations
  hosts: ios_xe_devices  # Targeted devices
#  hosts: r1  # Targeted devices
  gather_facts: false

#  vars_files:
#    - vars.yml

  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    ansible_user: jdoe
    ansible_password: 5uper5cret9assw0rd

  tasks:
    - name: Run show run and save to a file
      ios_config:
       backup: yes
       backup_options:
         filename: "{{ inventory_hostname }}-running-config.cfg"
         dir_path: /home/jdoe/cronjob1/backup/{{ timestamp }}_backup

#    - name: Print message when completed
#      debug: msg="{{ inventory_hostname }} - Backup to local storage completed"

- name: Copy backup files to SCP server
  hosts: localhost  # Run locally
  gather_facts: false

#  vars_files:
#    - vars.yml

  vars:
    passphrase_response: K0ala2023!@#$

  tasks:
    - name: Run SCP command
      ansible.builtin.expect:
        command: scp -r ./backup jdoe@192.168.127.151:/home/jdoe/.
        responses:
          "Enter passphrase for key '/home/jdoe/.ssh/id_ed25519':": "{{ passphrase_response }}"
      register: scp_output

    - name: Display SCP command output
      ansible.builtin.debug:
        var: scp_output.stdout_lines

#    - name: Print message when completed
#      debug: msg="Backup file transfer to SCP server completed"
