---
- name: Enable IP SCP server
  hosts: c8kv01
  gather_facts: false

  vars_files:
    - vars.yml

  vars:
    ios_file_name: "c8000v-universalk9.17.06.05.SPA.bin"
    scp_server_ip: "192.168.127.151"
    scp_username: "jdoe"
    scp_password: "Hugh060105"
    command_timeout: 900

  tasks:

    - name: Extend SSH timer to 99 mins
      cisco.ios.ios_config:
        commands:
          - line vty 0 15
          - exec-timeout 99 0

    - name: Enalbe ip scp server
      cisco.ios.ios_config:
        commands: ip scp server enable

    - name: COPY_NEW_IOS_FROM_SCP (192.168.127.151)
      ansible.netcommon.cli_command:
         command: 'copy scp://{{ scp_username }}:{{ scp_password }}@{{ scp_server_ip }}/{{ ios_file_name }} flash:/{{ ios_file_name }}'
         check_all: True
         prompt:
           - 'Destination filename'
         answer:
           - '{{ ios_file_name }}'
