- name: Copy httpd.conf file from f38c1 to local directory
  hosts: f38c1
  gather_facts: false
  collections:
    - ansible.builtin

  tasks:
    - name: Copy httpd.conf file
      fetch:
        src: /etc/httpd/conf/httpd.conf
        dest: ./
        flat: yes
