- hosts: f38c1
  become: true
  gather_facts: false
  collections:
    - ansible.builtin

  tasks:
  - name: Install unzip
    package:
      name: unzip # Install unzip on f38c1

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      dest: /usr/local/bin # File destination directory
      remote_src: yes # Tell Ansible that this is a remote source
      owner: root
      group: root

  - name: Check if Terraform is installed
    stat:
      path: /usr/local/bin/terraform
    register: terraform_installed

  - name: Get Terraform version
    command: /usr/local/bin/terraform version
    register: terraform_version
    changed_when: false
    when: terraform_installed.stat.exists

  - name: Print Terraform version
    debug:
      var: terraform_version.stdout_lines
    when: terraform_installed.stat.exists
