- hosts: all
  become: true
  collections:
    - ansible.builtin

  tasks:
    - name: Install packages on Linux
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
          - "{{ tmux_package }}"
          - "{{ tree_package }}"
        state: latest
        update_cache: yes
