- hosts: fedora
  become: yes
  gather_facts: false
  collections:
    - ansible.builtin

  tasks:
    - name: Reboot Fedora server
      reboot:
        reboot_timeout: 600
        test_command: uptime
        connect_timeout: 60
