- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: Remove apache2 package
    ansible.builtin.apt:
      name:  apache2
      state: absent

  - name: Remove php support for apache2
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
