---
- name: Update package cache on all Debian or Red Hat based OS
  hosts: all
  become: true

  tasks:
    - name: Update package cache on Red Hat distros
      ansible.builtin.dnf:
        update_cache: yes
      when: ansible_distribution in ['Fedora', 'Red Hat', 'CentOS']

    - name: Update package cache on Debian distros
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian',  'Pop!_OS']
