---
- name: Create Fortinet Administrators
  hosts: forti
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortios
  vars_files: vars.yml

  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
  - name: Create admins
    fortios_system_admin:
      vdom:  "root"
      state: "present"
      system_admin:
        accprofile: "super_admin"
        name: "{{ item.value.forti_username }}"
        password: "{{ item.value.forti_password }}"
    loop: "{{ lookup('dict',admins) }}"
    no_log: "True"
