---
- name: run show command
  hosts: palo
  gather_facts: false
  connection: local 
  vars_files: vars.yml

  collections: 
    -  paloaltonetworks.panos

  tasks:
   - name: show system info
     panos_op:
       provider: '{{ provider }}'
       cmd: 'show system info'
     register: show_info

   - name: Print info
     debug:
       var: show_info.stdout
